// Generated by Selenium IDE
package pt.ua.tqs;


import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.WebDriver;

import io.github.bonigarcia.seljup.BrowserType;
import io.github.bonigarcia.seljup.DockerBrowser;
import io.github.bonigarcia.seljup.SeleniumJupiter;
import pt.ua.tqs.webPages.ChoosePage;
import pt.ua.tqs.webPages.ConfirmationPage;
import pt.ua.tqs.webPages.FormPage;
import pt.ua.tqs.webPages.HomePageTest;

import java.util.concurrent.TimeUnit;



@ExtendWith(SeleniumJupiter.class)
public class FlightsTest {

  @Test
  public void TestFligths(@DockerBrowser(type = BrowserType.FIREFOX) WebDriver driver) throws InterruptedException {
      //Create object of HomePage Class
      driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

      HomePageTest home = new HomePageTest(driver);

      home.select_list_From("Portland");

      home.select_list_To("Dublin");

      home.clickOnFindButton();

      ChoosePage choosePage = new ChoosePage(driver);

      choosePage.clickOnFindButton("UA234");

      FormPage formPage = new FormPage(driver);

      formPage.setName("Tom");
      formPage.setAddress("123 London UK");
      formPage.setCity("London");
      formPage.setState("London");
      formPage.setZip("123456");
      formPage.select_Card_Tpe("Diner's Club");
      formPage.setCardNumber("123456");
      formPage.setCardMonth("11");
      formPage.setcreditCardYear("2023");
      formPage.setNameOnCard("Tom");
      formPage.clickButton();

      ConfirmationPage confirmationPage = new ConfirmationPage(driver);

      Thread.sleep(4000);
      
      confirmationPage.assertTitle("BlazeDemo Confirmation");


      driver.close();
      return;
  }

  }