// Generated by Selenium IDE
package pt.ua.tqs;

import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import io.github.bonigarcia.seljup.SeleniumJupiter;
import pt.ua.tqs.webPages.ChoosePage;
import pt.ua.tqs.webPages.ConfirmationPage;
import pt.ua.tqs.webPages.FormPage;
import pt.ua.tqs.webPages.HomePageTest;

import java.util.concurrent.TimeUnit;


import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;  


@ExtendWith(SeleniumJupiter.class)
public class FlightsTest {
  WebDriver driver;


  HomePageTest home;
  ChoosePage choosePage;
  FormPage formPage;
  ConfirmationPage confirmationPage;


    
      @When("I navigate to {string}")
      public void iNavigateTo(String url) {
          driver = new FirefoxDriver();
          driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
            
            home = new HomePageTest(driver,url);
  
      }
  
      @When("I choose the origin:{string} and the destiny:{string}")
      public void i_choose_the_origin_and_the_destiny(String string, String string2) {
          home.select_list_From(string); 
          home.select_list_To(string2); 
          home.clickOnFindButton();
      }
      
      @When("I select one of the fligths")
      public void i_select_one_of_the_fligths() {
        choosePage = new ChoosePage(driver);
          choosePage.clickOnFindButton("UA234"); 
      }
  
      @When("I write my name: {string}")
      public void i_write_my_name(String string) {
            formPage = new FormPage(driver);
          formPage.setName(string);
      }
      @When("I write my address:{string}")
      public void i_write_my_address(String string) {
          formPage.setAddress(string);
      }
      @When("I write my city:{string}")
      public void i_write_my_city(String string) {
          formPage.setCity(string);
      }
      @When("I write my State:{string}")
      public void i_write_my_state(String string) {
          formPage.setState(string);
      }
      @When("I write my Zip:{string}")
      public void i_write_my_zip(String string) {
          formPage.setZip(string);
      }
      @When("I select my Card Type:{string}")
      public void i_select_my_card_type(String string) {
          formPage.select_Card_Tpe(string);
      }
      @When("I write my Card Number:{string}")
      public void i_write_my_card_number(String string) {
          formPage.setCardNumber(string);
      }
      @When("I write my Credit Card month:{string}")
      public void i_write_my_credit_card_month(String string) {
          formPage.setCardMonth(string);
      }
      @When("I write my Credit Card Year:{string}")
      public void i_write_my_credit_card_year(String string) {
          formPage.setcreditCardYear(string);
      }
      @When("I write the Name on the Card:{string}")
      public void i_write_the_name_on_the_card(String string) {
          formPage.setNameOnCard(string);
      }
      @When("Click to confirm")
      public void click_to_conrim() {
          formPage.clickButton();
      }
      @Then("I should be in the {string} page")
      public void i_should_be_in_the_page(String string) throws java.lang.InterruptedException{ 
        confirmationPage = new ConfirmationPage(driver);

        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        confirmationPage.assertTitle("BlazeDemo Confirmation");
          
      }
  
  }